name: deploy

on: [push, pull_request]

# NOTE: the key is stored as a secret on GitHub. the address is not sensitive
env:
  AWS_USERNAME: ec2-user

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "hello world"
        run: echo "Today is $DAY_OF_WEEK! and you are $AWS_USERNAME"
