name: deploy

on: [push, pull_request]

jobs:
  - name: sanity check
    run: echo "logging in as $AWS_USERNAME@$AWS_ADDRESS"
  copy_files:
    runs-on: ubuntu-latest
    steps:
    - name: repo checkout
      uses: actions/checkout@v2
    - name: clean up previous workdir
      uses: fifsky/ssh-action@master
      with:
        command: |
          rm -rf ~/workdir
          mkdir -p ~/workdir
        host: $AWS_ADDRESS
        user: $AWS_USERNAME
        key: ${{secrets.AWS_KEY}}
