name: deploy

on: [push, pull_request]

jobs:
  update_files:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v2
      - name: clean up previous workdir
        uses: fifsky/ssh-action@master
        with:
          command: |
            rm -rf ~/workdir ||:
            mkdir -p ~//workdir
          host: ${{secrets.AWS_ADDRESS}}
          user: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}
      # NOTE: this action can be picky https://github.com/appleboy/ssh-action/issues/80
      - name: copy files over to aws
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.AWS_ADDRESS}}
          username: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}
          source: "requirements.txt"
          target: "~/workdir/"


