name: deploy

on: [push, pull_request]

jobs:
  system_check:
    runs-on: ubuntu-latest
    steps:
      - name: confirm docker install and permission
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker --version && groups | grep docker
          host: ${{secrets.AWS_ADDRESS}}
          user: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}

  update_files:
    runs-on: ubuntu-latest
    needs: system_check
    steps:
      - name: repo checkout
        uses: actions/checkout@v2
      - name: clean up previous workdir
        uses: fifsky/ssh-action@master
        with:
          command: |
            rm -rf ~/${{ github.event.repository.name }}
            mkdir -p ~/${{ github.event.repository.name }}
          host: ${{secrets.AWS_ADDRESS}}
          user: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}
      # NOTE: this action can be picky https://github.com/appleboy/ssh-action/issues/80
      - name: copy files over to aws
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.AWS_ADDRESS}}
          username: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}
          source: "app,nginx,scripts"
          target: "~/${{ github.event.repository.name }}/"
      - name: populate environment
        uses: fifsky/ssh-action@master
        with:
          command: |
            mkdir -p ~/${{ github.event.repository.name }}/app/assets/ 
            echo "${{ secrets.DJANGO_KEY }}" > ~/${{ github.event.repository.name }}/app/assets/django-secret-key.txt
            echo "hostname: \"${{ secrets.AWS_ADDRESS }}\"" >> ~/${{ github.event.repository.name }}/app/assets/deploy.yaml
          host: ${{secrets.AWS_ADDRESS}}
          user: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}

  launch_app:
    runs-on: ubuntu-latest
    needs: update_files
    steps:
      - name: launch app
        uses: fifsky/ssh-action@master
        with:
          command: ~/${{ github.event.repository.name }}/scripts/launch-app.sh -b -f
          host: ${{secrets.AWS_ADDRESS}}
          user: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}

  launch_nginx:
    runs-on: ubuntu-latest
    needs: update_files
    steps:
      - name: launch app
        uses: fifsky/ssh-action@master
        with:
          # For the moment, refresh every time
          command: ~/${{ github.event.repository.name }}/scripts/launch-nginx.sh -b -f
          host: ${{secrets.AWS_ADDRESS}}
          user: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}
