name: deploy

on: [push, pull_request]

jobs:
  system_check:
    runs-on: ubuntu-latest
    steps:
      - name: confirm docker install and permission
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker --version && groups | grep docker
          host: ${{secrets.AWS_ADDRESS}}
          user: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}

  update_files:
    runs-on: ubuntu-latest
    needs: system_check
    steps:
      - name: repo checkout
        uses: actions/checkout@v2
      - name: clean up previous workdir
        uses: fifsky/ssh-action@master
        with:
          command: |
            rm -rf ~/workdir
            mkdir -p ~//workdir
          host: ${{secrets.AWS_ADDRESS}}
          user: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}
      # NOTE: this action can be picky https://github.com/appleboy/ssh-action/issues/80
      - name: copy files over to aws
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.AWS_ADDRESS}}
          username: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}
          source: "amulet_flashcards,requirements.txt,Makefile,Dockerfile"
          target: "~/workdir/"
      - name: add django secret key
        uses: fifsky/ssh-action@master
        with:
          command: |
            mkdir -p ~/workdir/amulet_flashcards/assets/ 
            echo "${{ secrets.DJANGO_KEY }}" > ~/workdir/amulet_flashcards/assets/django-secret-key.txt
          host: ${{secrets.AWS_ADDRESS}}
          user: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}

  launch_app:
    runs-on: ubuntu-latest
    needs: update_files
    steps:
      - name: launch app
        uses: fifsky/ssh-action@master
        with:
          command: ~/workdir/scripts/run-app.sh -b -f
          host: ${{secrets.AWS_ADDRESS}}
          user: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}
