name: deploy

on: [push, pull_request]

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
    - name: sanity check
      run: echo "logging in as ${{ env.AWS_USERNAME }}@${{ env.AWS_ADDRESS }}"
    - name: repo checkout
      uses: actions/checkout@v2
    - name: clean up previous workdir
      uses: fifsky/ssh-action@master
      with:
        command: |
          rm -rf ~/workdir
          mkdir -p ~/workdir
        host: ${{ env.AWS_ADDRESS }}
        user: ${{ env.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
